# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ee_CacWmbNC9urarYxNBbMSh-_Mm39dM
"""

from huggingface_hub import login
from google.colab import userdata
hf_token=userdata.get("HF_TOKEN")
login(hf_token,add_to_git_credential=True)

from IPython.display import display
from diffusers import AutoPipelineForText2Image
import torch

torch.cuda.empty_cache()

pipe = AutoPipelineForText2Image.from_pretrained("stabilityai/sdxl-turbo", torch_dtype=torch.float16, variant="fp16")
pipe.to("cuda")
prompt= "A class of student learning Al engineering on a vibrant pop-ar style"
image=pipe(prompt=prompt, num_inference_steps=4, guidance_scale=7.0).images[0]
display(image)

import IPython
IPython.Application.instance().kernel.do_shutdown(True)

from diffusers.utils.import_utils import USE_SAFETENSORS
from IPython.display import display
from diffusers import DiffusionPipeline
import torch
pipe=DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0",torch_dtype=torch.float16,use_safetensor=True)
pipe.to("cuda")
prompt="A class of students learning AI engineering on a vibrant pop-ar style"
image=pipe(prompt=prompt,num_inference_steps=30,guidance_scale=7.5).images[0]
display(image)

import IPython
IPython.Application.instance().kernel.do_shutdown(True)

from diffusers import DiffusionPipeline
import torch
base=DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0",torch_dtype=torch.float16,variant="fp16",use_safetensor=True)
base.to("cuda")
refiner=DiffusionPipeline.from_pretrained("stabilityai/stable-diffusion-xl-refiner-1.0",torch_dtype=torch.float16,text_encoder_2=base.text_encoder_2, vae=base.vae,variant="fp16",use_safetensor=True)
refiner.to("cuda")
n_steps = 40
high_noise_frac = 0.8
prompt="A majestic loin jumb from stone in night time"
image=base(prompt=prompt,num_inference_steps=n_steps,denoising_strength=high_noise_frac,output_type="latent").images
image=refiner(prompt=prompt,num_inference_steps=n_steps,denoising_strength=high_noise_frac,image=image).images[0]
display(image)

import IPython
IPython.Application.instance().kernel.do_shutdown(True)

### FluxPipeline is the Hugging Face diffusers pipeline built specifically for running FLUX.1 text-to-image models (developed by Black Forest Labs).

import torch
from diffusers import FluxPipeline
from IPython.display import display
from datetime import datetime
pipe=FluxPipeline.from_pretrained("black-forest-labs/FLUX.1-schnell", torch_dtype=torch.bfloat16).to("cuda")
generator = torch.Generator(device="cuda").manual_seed(0)
prompt = "A class of data scientists learning AI engineering in a vibrant high-energy pop-art style"
image = pipe(
    prompt,
    guidance_scale=0.0,
    num_inference_steps=4,
    max_sequence_length=256,
    generator=generator
).images[0]
display(image)
stop = datetime.now()